create-messages-table=CREATE TABLE IF NOT EXISTS messages (id INTEGER IDENTITY PRIMARY KEY, author VARCHAR(30), content VARCHAR(1000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN DEFAULT FALSE)
twenty-last-messages=SELECT * FROM (SELECT * FROM messages WHERE is_deleted = FALSE ORDER BY created_at DESC LIMIT 20) AS sq ORDER BY created_at ASC
get-message=SELECT * FROM messages WHERE Id = ? AND is_deleted = FALSE
get-all-messages=SELECT * FROM messages
delete-message=UPDATE messages SET is_deleted = TRUE WHERE Id = ?
save-message=UPDATE messages SET author = ?, content = ? WHERE Id = ?
create-message=INSERT INTO messages (author, content) VALUES (?, ?)
create-users-table=CREATE TABLE IF NOT EXISTS users (id INTEGER IDENTITY PRIMARY KEY, username VARCHAR(30) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL)
get-user=SELECT * FROM users WHERE username = ?
create-user=INSERT INTO users (username, password) VALUES (?, ?)
